import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
// import { getServerSession } from 'next-auth';
import { NavMenu } from '../components';
import { Providers } from '../components/SessionProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // const session = await getServerSession();
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Providers>
          <main className='mx-auto flex max-w-5xl gap-2 text-2xl'>
            <NavMenu />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
